name: Deploy to Public Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to public branch
        run: |
          echo "Current directory contents:"
          ls -la
          
          echo "Building project..."
          npm run build
          
          echo "Dist directory contents:"
          ls -la dist
          
          echo "Deploying to gh-pages..."
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Save dist folder
          mv dist ../dist-temp
          
          # Create new orphan branch
          git checkout --orphan gh-pages
          git reset --hard
          git clean -fd
          
          # Move dist contents back
          mv ../dist-temp/* .
          
          # Add and commit
          git add .
          git commit -m "Deploy to public branch"
          git push -f origin gh-pages