name: Deploy to Public Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          
      - name: Deploy to public branch
        run: |
          if [ -d "dist" ]; then
            echo "Found dist directory"
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git checkout --orphan gh-pages
            git rm -rf .
            mv dist/* ./ || exit 1
            rm -rf dist
            echo "Files moved successfully"
            ls -la
            git add .
            git commit -m "Deploy to public branch"
            git push --force origin gh-pages
          else
            echo "Directory structure:"
            ls -la
            echo "Dist directory not found. Build may have failed."
            exit 1
          fi