Sure, here's the proposed content for the /.github/workflows/deploy.yml file:

name: Deploy to Public Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to public branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Deploy to public branch"
          git push --force origin gh-pages